/*
 * This header for constants clk index STMicroelectronics
 * STiD325 SoC.
 */
#ifndef _DT_BINDINGS_CLK_STID325
#define _DT_BINDINGS_CLK_STID325

/* CLOCKGEN B0 */
#define CLK_ST40		CLK_S_B0_FLEXGEN 0
#define CLK_ST231		CLK_S_B0_FLEXGEN 1
#define CLK_ICN_CPU		CLK_S_B0_FLEXGEN 2
#define CLK_ICN_L0L1		CLK_S_B0_FLEXGEN 3
#define CLK_ICN_ST231_40	CLK_S_B0_FLEXGEN 4
#define CLK_ICN_REG_0		CLK_S_B0_FLEXGEN 6
#define CLK_ATCLK		CLK_S_B0_FLEXGEN 7
#define CLK_TRACE		CLK_S_B0_FLEXGEN 8
#define CLK_EXT_A5X		CLK_S_B0_FLEXGEN 9
#define CLK_TIMER_A5X		CLK_S_B0_FLEXGEN 10
#define CLK_TIMER_LPC		CLK_S_B0_FLEXGEN 11
#define CLK_DDR4SS_0_EXT	CLK_S_B0_FLEXGEN 12
#define CLK_PMB_A5X		CLK_S_B0_FLEXGEN 13
#define CLK_PROMIP_CPU		CLK_S_B0_FLEXGEN 14
#define CLK_30_SATA		CLK_S_B0_FLEXGEN 16
#define CLK_200_SATA		CLK_S_B0_FLEXGEN 17

/* CLOCKGEN B1 */
#define CLK_SLIM_CC		CLK_S_B1_FLEXGEN 0
#define CLK_ICN_BD		CLK_S_B1_FLEXGEN 1
#define CLK_MMC_0		CLK_S_B1_FLEXGEN 2
#define CLK_SPI			CLK_S_B1_FLEXGEN 3
#define CLK_SC			CLK_S_B1_FLEXGEN 4
#define CLK_ICN_REG_2		CLK_S_B1_FLEXGEN 5
#define CLK_PROC_STFE		CLK_S_B1_FLEXGEN 6
#define CLK_TSOUT_0		CLK_S_B1_FLEXGEN 7
#define CLK_TSOUT_1		CLK_S_B1_FLEXGEN 8
#define CLK_PROMIP_MAC		CLK_S_B1_FLEXGEN 9
#define CLK_ICN_CCL2		CLK_S_B1_FLEXGEN 10
#define CLK_ICN_TS		CLK_S_B1_FLEXGEN 11
#define CLK_FDMA		CLK_S_B1_FLEXGEN 12
#define CLK_FLASH		CLK_S_B1_FLEXGEN 13
#define CLK_NAND		CLK_S_B1_FLEXGEN 14
#define CLK_MMC_1		CLK_S_B1_FLEXGEN 15
#define CLK_ICN_LPM		CLK_S_B1_FLEXGEN 16
#define CLK_BACKUP_TO_CLKGEN_D_1	CLK_S_B1_FLEXGEN 17

/* CLOCKGEN D0 */
#define CLK_TELSS_FDMA		CLK_S_D0_FLEXGEN 0
#define CLK_PROC_FP3		CLK_S_D0_FLEXGEN 1
#define CLK_ICN_HSIF_NET	CLK_S_D0_FLEXGEN 2
#define CLK_32KB_HSIF		CLK_S_D0_FLEXGEN 3
#define CLK_ICN_REG_1		CLK_S_D0_FLEXGEN 4
#define CLK_PCM_TELSS		CLK_S_D0_FLEXGEN 5
#define CLK_ZARLINK		CLK_S_D0_FLEXGEN 6
#define CLK_PROMIP_NTW		CLK_S_D0_FLEXGEN 7
#define CLK_ETH0_PHYCLK_INT	CLK_S_D0_FLEXGEN 8
#define CLK_ETH1_PHYCLK_INT	CLK_S_D0_FLEXGEN 9
#define CLK_ETH2_PHYCLK_INT	CLK_S_D0_FLEXGEN 10
#define CLK_250_TO_CLKGEN_D_1	CLK_S_D0_FLEXGEN 12

/* CLOCKGEN D1 */
#define CLK_CPU_ECM		CLK_S_D1_FLEXGEN 0
#define CLK_LPC_DS31_PHY	CLK_S_D1_FLEXGEN 1
#define CLK_ICN_DS		CLK_S_D1_FLEXGEN 2
#define CLK_ICN_US		CLK_S_D1_FLEXGEN 3
#define CLK_CMCI_DS		CLK_S_D1_FLEXGEN 4
#define CLK_CMCI_US		CLK_S_D1_FLEXGEN 5
#define CLK_D31RX		CLK_S_D1_FLEXGEN 6
#define CLK_COMMON_216		CLK_S_D1_FLEXGEN 7
#define CLK_COMMON_54		CLK_S_D1_FLEXGEN 8
#define CLK_COMMON_PROC		CLK_S_D1_FLEXGEN 9
#define CLK_IC_DS_OFDM		CLK_S_D1_FLEXGEN 10
#define CLK_DS_BRG		CLK_S_D1_FLEXGEN 11
#define CLK_US_BRG		CLK_S_D1_FLEXGEN 12
#define CLK_DSOFDM_PACK_PROC	CLK_S_D1_FLEXGEN 13
#define CLK_DS_MAC		CLK_S_D1_FLEXGEN 15
#define CLK_US_MAC		CLK_S_D1_FLEXGEN 16
#define CLK_DQAM_108		CLK_S_D1_FLEXGEN 17
#define CLK_ICN_REG_3		CLK_S_D1_FLEXGEN 18
#define CLK_ICN_REG_4		CLK_S_D1_FLEXGEN 19
#define CLK_LP_TO_CLKGENB0	CLK_S_D1_FLEXGEN 20
#define CLK_LP_TO_CLKGENB1	CLK_S_D1_FLEXGEN 21
#define CLK_LP_TO_CLKGEND0	CLK_S_D1_FLEXGEN 22

#endif
