/*
 * This header for constants clk index STMicroelectronics
 * STiH390 SoC.
 */
#ifndef _DT_BINDINGS_CLK_STIH390
#define _DT_BINDINGS_CLK_STIH390

/* Clockgen_A0_FlexGen */
#define CLK_ICN_LMI			CLK_S_A0_FLEXGEN 0

/* Clockgen_C0_FlexGen */
#define CLK_SLIM_CC		CLK_S_C0_FLEXGEN 0
#define CLK_SPI			CLK_S_C0_FLEXGEN 1
#define CLK_FLASH		CLK_S_C0_FLEXGEN 2
#define CLK_ICN_BD		CLK_FLASH
#define CLK_MMC_0		CLK_S_C0_FLEXGEN 3
#define CLK_PERIPH_TS		CLK_S_C0_FLEXGEN 4
#define CLK_EXT2F_A9		CLK_S_C0_FLEXGEN 5
#define CLK_ICN_TS		CLK_S_C0_FLEXGEN 6
#define CLK_NAND		CLK_S_C0_FLEXGEN 7
#define CLK_MMC_1		CLK_S_C0_FLEXGEN 8
#define CLK_ST231_GP_2		CLK_S_C0_FLEXGEN 9
#define CLK_ST231_VDEC		CLK_S_C0_FLEXGEN 10
#define CLK_ST231_GP_0		CLK_S_C0_FLEXGEN 11
#define CLK_ST231_GP_1_AUDIO	CLK_S_C0_FLEXGEN 12
#define CLK_ETH_GMAC_S		CLK_S_C0_FLEXGEN 13
#define CLK_GMAC_S_PHYCLK	CLK_S_C0_FLEXGEN 14
#define CLK_ETH_GMAC_W		CLK_S_C0_FLEXGEN 15
#define CLK_GMAC_W_PHYCLK	CLK_S_C0_FLEXGEN 16
#define CLK_STBE		CLK_S_C0_FLEXGEN 17
#define CLK_HEVC_H264		CLK_S_C0_FLEXGEN 18
#define CLK_HEVC		CLK_HEVC_H264
#define CLK_H264		CLK_HEVC_H264
#define CLK_AVSP		CLK_S_C0_FLEXGEN 19
#define CLK_TIMER_A9		CLK_S_C0_FLEXGEN 20
#define CLK_SLIM_VDEC		CLK_S_C0_FLEXGEN 21
#define CLK_DEC_JPEG		CLK_S_C0_FLEXGEN 22
#define CLK_WIFI		CLK_S_C0_FLEXGEN 23
#define CLK_RX_ICN_L0L1		CLK_S_C0_FLEXGEN 24
#define CLK_FRC_1		CLK_S_C0_FLEXGEN 25
#define CLK_FRC_1_PAD		CLK_S_C0_FLEXGEN 26
#define CLK_DVP_PROC		CLK_S_C0_FLEXGEN 27
#define CLK_TX_ICN_L0L1		CLK_S_C0_FLEXGEN 28
#define CLK_SYS_CLK_OUT		CLK_S_C0_FLEXGEN 29
#define CLK_SYSTEM_STFE		CLK_S_C0_FLEXGEN 30
#define CLK_SLIM_FDMA_1		CLK_S_C0_FLEXGEN 32
#define CLK_ATB			CLK_S_C0_FLEXGEN 33
#define CLK_TRACE		CLK_S_C0_FLEXGEN 34
#define CLK_BDISP		CLK_S_C0_FLEXGEN 35
#define CLK_PROC_VDP		CLK_S_C0_FLEXGEN 36
#define CLK_DSS			CLK_S_C0_FLEXGEN 37
#define CLK_LPC			CLK_S_C0_FLEXGEN 39
#define CLK_GPU			CLK_S_C0_FLEXGEN 40
#define CLK_ICN_WIFI		CLK_S_C0_FLEXGEN 41
#define CLK_ICN_DISP		CLK_S_C0_FLEXGEN 42
#define CLK_ICN_CPU		CLK_S_C0_FLEXGEN 43
#define CLK_PERIPH_WIFI		CLK_S_C0_FLEXGEN 44
#define CLK_SLIM_FDMA_0		CLK_S_C0_FLEXGEN 45
#define CLK_PERIPH_DISP		CLK_S_C0_FLEXGEN 46
#define CLK_PERIPH_CPU		CLK_S_C0_FLEXGEN 47

/* Clockgen_D0_FlexGen */
#define CLK_PCM_0		CLK_S_D0_FLEXGEN 0
#define CLK_PCM_1		CLK_S_D0_FLEXGEN 1
#define CLK_PCM_2		CLK_S_D0_FLEXGEN 2
#define CLK_SPDIF		CLK_S_D0_FLEXGEN 3
#define CLK_PCMR_0_MASTER	CLK_S_D0_FLEXGEN 4
#define CLK_MCLK_OUT		CLK_S_D0_FLEXGEN 5

/* Clockgen_D1_FlexGen */
#define CLK_PIX_MAIN_DISP	CLK_S_D1_FLEXGEN 0
#define CLK_PIX_AUX_DISP	CLK_S_D1_FLEXGEN 1
#define CLK_PIX_HDDAC		CLK_S_D1_FLEXGEN 2
#define CLK_HDDAC		CLK_S_D1_FLEXGEN 3
#define CLK_TVOUT_SDDAC		CLK_S_D1_FLEXGEN 6
#define CLK_PIX_HDMI		CLK_S_D1_FLEXGEN 7
#define CLK_DENC		CLK_S_D1_FLEXGEN 8
#define CLK_REF_HDMIPHY		CLK_S_D1_FLEXGEN 9
#define CLK_TMDS_HDMI		CLK_S_D1_FLEXGEN 10
#define CLK_PROC_HQVDP		CLK_S_D1_FLEXGEN 11
#define CLK_IQI_HQVDP		CLK_S_D1_FLEXGEN 12
#define CLK_PROC_MIXER		CLK_S_D1_FLEXGEN 13
#define CLK_PROC_GDP_COMPO	CLK_S_D1_FLEXGEN 14
#define CLK_PWM			CLK_S_D1_FLEXGEN 15
#define CLK_FRC_0		CLK_S_D1_FLEXGEN 16
#define CLK_FRC_0_PAD		CLK_S_D1_FLEXGEN 17
#define CLK_FRC_2		CLK_S_D1_FLEXGEN 18
#define CLK_HDMI_PHASE_REG	CLK_S_D1_FLEXGEN 40

#endif
